name: List PR Changes

on:
  pull_request:

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List PR Changes
        uses: dorny/changed-files@v1
        id: files
        with:
          only: |
            A # List added files
            M # List modified files

      - name: Print PR Changes
        run: |
          echo "Added or modified files:"
          echo "${{ steps.files.outputs.files }}"