name: Bidder Info Update

on:
  push:
    paths:
      - './static/bidder-info/**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if any .yaml file is updated
        id: check-bidder-info-updated
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^static/bidder-info/.*\.yaml$'; then
            updated_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^static/bidder-info/.*\.yaml$')
            echo "Updated Files: $updated_files"
          
            for file in $updated_files; do
              url_changed=$(yq eval ".userSync.redirect.url as \$new | input | .userSync.redirect.url as \$old | if \$new == \$old then empty else \$new end" $file <(git show ${GITHUB_SHA}:$file) | grep -q '^[^ ]' && echo true || echo false)
              macro_changed=$(yq eval ".userSync.userMacro as \$new | input | .userSync.userMacro as \$old | if \$new == \$old then empty else \$new end" $file <(git show ${GITHUB_SHA}:$file) | grep -q '^[^ ]' && echo true || echo false)
              if [ "$url_changed" = "true" ] || [ "$macro_changed" = "true" ]; then
                echo "URL/UserMacro is updated"
              fi
            done
          fi
