name: Check YAML file changes

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-yaml-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check YAML files
        run: |
          if git diff --name-only HEAD^..HEAD | grep --quiet '\.yaml$'; then
            echo "A YAML file was modified or added"
          else
            echo "No YAML files were modified or added"
          fi