name: List PR Changes

on:
  pull_request:
    paths:
      - 'static/bidder-info/**/**.yaml'

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
