name: Check Bidder Info Yaml Files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_yaml_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Check for changes in static/bidder-info/*.yaml files
        id: check_changes
        run: |
          changed_files=$(git diff --name-only HEAD^ HEAD | grep -E '^static/bidder-info/.*\.yaml$' || true)
          echo "::set-output name=changed_files::$changed_files"

      - name: Check userSync.redirect.url in updated/added YAML files
        if: steps.check_changes.outputs.changed_files != ''
        run: |
          for file in ${{ steps.check_changes.outputs.changed_files }}; do
            if [ -f "$file" ]; then
              cat "$file"
              if git diff HEAD^ HEAD --quiet -- "$file"; then
                echo "File $file was added in this PR"
                if yq eval '.userSync.redirect.url' "$file" > /dev/null; then
                  echo "userSync.redirect.url found in $file"
                else
                  echo "userSync.redirect.url not found in $file"
                fi
              else
                echo "File $file was updated in this PR"
                if [ yq eval '.userSync.redirect.url' "$file" > /dev/null ] && [ git diff --unified=0 HEAD^ HEAD -- "$file" | grep -q '^\+ *url:' ]; then
                  echo "userSync.redirect.url was updated in $file"
                else
                  echo "userSync.redirect.url was not updated in $file"
                fi
                git diff --unified=0 HEAD^ HEAD -- "$file"
              fi
            fi
          done
