name: Bidder Info Update

on:
  push:
    paths:
      - 'static/bidder-info/**/*.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if any .yaml file is updated
        id: check-bidder-info-updated
        run: |
          # Check if any .yaml file in static/bidder-info/{any-adapter} is updated
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^static/bidder-info/.*\.yaml$'; then
            updated_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^static/bidder-info/.*\.yaml$')
            echo "Updated YAML files: $updated_files"

            # Check if the URL in each updated YAML file is updated
            for file in $updated_files; do
              url_changed=$(git diff ${{ github.event.before }} ${{ github.event.after }} -- $file | yq e '.userSync.redirect.url' - | diff - <(git show ${GITHUB_SHA}:$file | yq e '.userSync.redirect.url' -) | wc -l)
              if [ "$url_changed" -gt 0 ]; then
                echo "URL is updated in $file"
              else
                echo "URL is not updated in $file"
              fi
            done
          fi
