name: List PR Changes

on:
  pull_request:

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List PR Changes
        uses: jitterbit/get-changed-files@v1
        id: changed_files

      - name: Print PR Changes
        run: |
          echo "Added or modified files:"
          echo "${{ steps.changed_files.outputs.files }}"
