name: Check userSync.redirect.url in YAML files

on:
  pull_request:
    paths:
      - 'static/bidder-info/*.yaml'
    types: [opened, reopened, synchronize]

jobs:
  check_yaml_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Install yq
        run: sudo apt update && sudo apt install yq -y

      - name: Check YAML files
        run: |
          set -e
          for file in $(git diff --name-only ${GITHUB_BASE_REF}..${GITHUB_HEAD_REF} | grep -E '^static/bidder-info/.*\.yaml$'); do
            if [[ $(yq eval '.userSync.redirect.url' "$file") != "" ]]; then
              echo "userSync.redirect.url was updated or added in $file"
              exit 1
            fi
          done