name: Check YAML file changes

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-yaml-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check YAML file changes
        run: |
          if git diff --name-only HEAD~1 | grep -qE '\.yml$'; then
            echo "A YAML file was added or updated in this PR."
          else
            echo "No YAML files were added or updated in this PR."
          fi