name: Bidder Info Update

on:
  push:
    paths:
      - 'static/bidder-info/**/*.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if any .yaml file is updated
        id: check-bidder-info-updated
        run: |
          # Check if any .yaml file in static/bidder-info/{any-adapter} is updated
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^static/bidder-info/.*\.yaml$'; then
            updated_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^static/bidder-info/.*\.yaml$')
            echo "Updated YAML files: $updated_files"
          
            # Check if the URL in each updated YAML file is updated
            for file in $updated_files; do
              # Skip checking for URL changes in removed files
              if [ ! -f "$file" ]; then
                echo "File $file was removed, skipping URL check"
                continue
              fi
              # Extract the URL property from the updated YAML file and the previous commit's YAML file and compare them
              url_changed=$(git diff ${{ github.event.before }} ${{ github.event.after }} -- $file | yq e '.url' - 2> /dev/null | diff - <(git show ${GITHUB_SHA}:$file 2> /dev/null | yq e '.url' -) | wc -l)
              # Check if URL was removed from the file
              url_removed=$(yq e '.url' $file 2> /dev/null | grep -Eq '^$' && echo true || echo false)
              if [ $url_changed -gt 0 ] && [ "$url_removed" = "false" ]; then
                echo "URL in file $file is updated"
              else
                echo "URL in file $file is not updated"
              fi
            done
          fi
