name: Check user sync url

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List PR Changes
        run: |
          git fetch --all
          git diff --name-only origin/${{ github.event.pull_request.head.ref }}..${{ github.event.pull_request.base.ref }}