name: Check Bidder Info Yaml Files

on:
  push:
    paths:
      - 'static/bidder-info/**.yaml'

jobs:
  check_yaml_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if any .yaml file is updated
        id: check-bidder-info-updated
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^static/bidder-info/.*\.yaml$'; then
            updated_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^static/bidder-info/.*\.yaml$')
            echo "Updated Files: $updated_files"
          
            for file in $updated_files; do
              if [ -f "$file" ]; then
                if git diff --name-only --diff-filter=A ${{ github.event.before }} ${{ github.event.after }} | grep -q "^$file$"; then
                  echo "File $file was added in this PR"
                  redirectURL="$(yq eval '.userSync.redirect.url' "$file")"
                  length=$(echo -n "$redirectURL" | wc -c)
                  if [ "$redirectURL" == null ] || [ $length == 0 ]; then
                    echo "userSync.redirect.url not found in $file"
                  else
                    echo "userSync.redirect.url found in $file"
                  fi
                else
                  echo "File $file was updated in this PR"
                  prChanges=$(yq eval '.userSync.redirect.url' "$file")
                  echo "PR changes: $prChanges"
                  masterChanges=$(yq eval '.userSync.redirect.url' <(git show origin/master:$file))
                  echo "Master changes: $masterChanges"
                  if [ "$prChanges" != "$masterChanges" ]; then
                    echo "userSync.redirect.url was updated in $file"
                  else
                    echo "userSync.redirect.url was not updated in $file"
                  fi
                fi
              else
                echo "File $file does not exist"
              fi
            done
          fi