name: Check user sync url

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check YAML file
        run: |
          if git diff-tree --no-commit-id --name-only -r HEAD | grep --quiet '\.yaml$'; then
            if yq eval '.userSync.redirect.url' $(git diff --unified=0 HEAD^..HEAD -- '*.yaml'); then
              echo "The userSync.redirect.url property was added or updated in the YAML file."
            else
              echo "The userSync.redirect.url property was not added or updated in the YAML file."
            fi
          else
            echo "No YAML files were modified or added."
          fi