name: Bidder Info Update

on:
  push:
    paths:
      - 'static/bidder-info/**/*.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if any .yaml file is updated
        id: check-bidder-info-updated
        run: |
          # Check if any .yaml file in static/bidder-info/{any-adapter} is updated
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^static/bidder-info/.*\.yaml$'; then
            # Get the list of updated YAML files
            updated_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^static/bidder-info/.*\.yaml$')
            echo "Updated YAML files: $updated_files"
          
            # Check if the URL in each updated YAML file is updated
            for file in $updated_files; do
              url_changed=$(git diff ${{ github.event.before }} ${{ github.event.after }} -- $file | grep -q '^[+ ]*url:' && echo true || echo false)
              echo "Is URL changed: $url_changed"
              if [ "$url_changed" = "true" ]; then
                echo "URL is updated"
                break
              fi
            done
          fi
