name: Bidder Info Update

on:
  push:
    paths:
      - 'static/bidder-info/**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if any .yaml file is updated
        id: check-bidder-info-updated
        run: |
          file_path="static/bidder-info/"
          for file in $(git diff-tree --no-commit-id --name-only -r HEAD | grep "^$file_path"); do
            if [[ ! -e "$file" ]]; then
              echo "File $file does not exist"
              continue
            fi

            url_changed=$(yq eval ".userSync.redirect.url as \$new | input | .userSync.redirect.url as \$old | if \$new == \$old then empty else \$new end" $file <(git show origin/master:$file 2> /dev/null))
            macro_changed=$(yq eval ".userSync.redirect.userMacro as \$new | input | .userSync.redirect.userMacro as \$old | if \$new == \$old then empty else \$new end" $file <(git show origin/master:$file 2> /dev/null))

            if [ -n "$url_changed" ] || [ -n "$macro_changed" ]; then
              echo "URL/UserMacro is updated in file $file"
            fi
          done
